### ISSUE TITLE
kirby-reporter doesn't get installed to site/plugins

### ISSUE THREAD

**Issue by felixhaeberle** [gearsdigital/kirby-reporter#20]
The `kirby-reporter` plugin doesn't get installed to `site/plugins` and is in the `vendor` folder.
Fix: https://getkirby.com/docs/guide/plugins/plugin-setup-basic 
Use `getkirby/composer-installer` to install it to `site/plugins`

**Comment by felixhaeberle** [comment]
see #21

**Comment by gearsdigital** [comment]
I'll have a look at #21 and pepare a new release. Thanks for reporting this @felixhaeberle!
