### ISSUE TITLE
make report-form work on webpage (available outside of the panel)?

### ISSUE THREAD

**Issue by jhercher** [gearsdigital/kirby-reporter#57]
Would it be possible to make the plugin work for the frontend as well?
There could be a small widget visible to logged in users, where they could leave feedback immediately when they see a bug, or have an idea.
That would make it more fluid, as you don't have to go finding the page in the panel. 

Just wondering if this would be out of scope, or even impossible...

Anyways, great work - really appreciate it.
-Johannes

**Comment by gearsdigital** [comment]
Hello @jhercher, thank you very much for your input. It's been a while that I've worked on this plugin 😵

I like the idea a lot and have had similar thoughts before. That would be a really great addition... but I regret to say that I decided against this feature. There is currently no way of encapsulation, and it would probably lead to conflicting styles and unexpected behavior with existing functionality of your site.

You could try to create the widget by yourself and provide a link the related panel page.

Kind regards!
