### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by mrflix** [gearsdigital/kirby-reporter#6]
Would be cool to see a screenshot of the UI to get an idea of the plugin.

**Comment by gearsdigital** [comment]
Sure thing @mrflix :) I'll add a screenshot to the readme.

For now just head over to the Kirby Plugin Registry: https://github.com/getkirby/plugins/issues/90

**Comment by mrflix** [comment]
Ah nice, thanks! Two thoughts: 1. I would do the screenshot without the browser 2. It would be interesting to also see button on the dashboard thats leading to the new issue screen.

**Comment by gearsdigital** [comment]
Thanks for your feedback.. I'll take care of this :)

**Comment by gearsdigital** [comment]
![screenshot](https://user-images.githubusercontent.com/965069/60097385-95a1cf00-9753-11e9-8650-34a9b4d0b7c0.png)

**Comment by gearsdigital** [comment]
@mrflix I added the screenshot to the readme file.

**Comment by mrflix** [comment]
Looks good!

**Comment by gearsdigital** [comment]
![screencapture](https://user-images.githubusercontent.com/965069/60726156-2c803f80-9f3b-11e9-97f8-43b5b71689ab.gif)
